/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeGrowthChannelStrategyRouteImport } from './routes/youtube-growth-channel-strategy'
import { Route as WebsiteDevelopmentUnitedStatesRouteImport } from './routes/website-development-united-states'
import { Route as WebsiteDesignDevelopmentRouteImport } from './routes/website-design-development'
import { Route as UnitedStateHomeRouteImport } from './routes/united-stateHome'
import { Route as UiUxDesignProductEngineeringRouteImport } from './routes/ui-ux-design-product-engineering'
import { Route as TermsConditionRouteImport } from './routes/terms-condition'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SocialMediaMarketingRouteImport } from './routes/social-media-marketing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchVisibilityRouteImport } from './routes/search-visibility'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as PublicRelationsReputationManagementRouteImport } from './routes/public-relations-reputation-management'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PodcastStrategyProductionRouteImport } from './routes/podcast-strategy-production'
import { Route as PerformanceMarketingRouteImport } from './routes/performance-marketing'
import { Route as PackagingProductBrandingRouteImport } from './routes/packaging-product-branding'
import { Route as MotionGraphicsAnimationRouteImport } from './routes/motion-graphics-animation'
import { Route as MobileAppDevelopmentRouteImport } from './routes/mobile-app-development'
import { Route as MarketingCommunicationRouteImport } from './routes/marketing-communication'
import { Route as MarketingAutomationRouteImport } from './routes/marketing-automation'
import { Route as LogoVisualIdentityRouteImport } from './routes/logo-visual-identity'
import { Route as InfluencerAdvocacyCommunityMarketingRouteImport } from './routes/influencer-advocacy-community-marketing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GrowthMarketingRouteImport } from './routes/growth-marketing'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as EventMarketingBrandExperiencesRouteImport } from './routes/event-marketing-brand-experiences'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as D2cRetailbrandRouteImport } from './routes/d2c-retailbrand'
import { Route as CrmErpSolutionsRouteImport } from './routes/crm-erp-solutions'
import { Route as CorporateFilmsVideoProductionRouteImport } from './routes/corporate-films-video-production'
import { Route as CorporateCommunicationDesignRouteImport } from './routes/corporate-communication-design'
import { Route as CorporateB2bGrowthMarketingRouteImport } from './routes/corporate-b2b-growth-marketing'
import { Route as ConversionOptimizationRouteImport } from './routes/conversion-optimization'
import { Route as ContentMarketingRouteImport } from './routes/content-marketing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseRexelloCastorsRouteImport } from './routes/case-rexello-castors'
import { Route as CaseMosUtilityRouteImport } from './routes/case-mos-utility'
import { Route as CaseLivingConceptsRouteImport } from './routes/case-living-concepts'
import { Route as CaseKuwalSanamRouteImport } from './routes/case-kuwal-sanam'
import { Route as CaseCosmosSealsRouteImport } from './routes/case-cosmos-seals'
import { Route as CaseAmigoAcademyRouteImport } from './routes/case-amigo-academy'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrandingCreativeRouteImport } from './routes/branding-creative'
import { Route as BrandStrategyRouteImport } from './routes/brand-strategy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsGrowthIntelligenceRouteImport } from './routes/analytics-growth-intelligence'
import { Route as AiWorkflowAutomationRouteImport } from './routes/ai-workflow-automation'
import { Route as AiTransformationRouteImport } from './routes/ai-transformation'
import { Route as AiStrategyReadinessAssessmentRouteImport } from './routes/ai-strategy-readiness-assessment'
import { Route as AiCustomerExperienceSolutionsRouteImport } from './routes/ai-customer-experience-solutions'
import { Route as AiContentMarketingSystemsRouteImport } from './routes/ai-content-marketing-systems'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessStoriesEnterpriseExperienceRouteImport } from './routes/success-stories.enterprise-experience'
import { Route as IndustriesSaasTechnologyRouteImport } from './routes/industries_.saas-technology'
import { Route as IndustriesRealEstateRouteImport } from './routes/industries_.real-estate'
import { Route as IndustriesManufacturingRouteImport } from './routes/industries_.manufacturing'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries_.healthcare'
import { Route as IndustriesFintechRouteImport } from './routes/industries_.fintech'
import { Route as IndustriesEducationRouteImport } from './routes/industries_.education'
import { Route as IndustriesD2cRetailbrandcopy2RouteImport } from './routes/industries_.d2c-retailbrand copy 2'
import { Route as IndustriesD2cRetailbrandRouteImport } from './routes/industries_.d2c-retailbrand'
import { Route as IndustriesArchitectureRouteImport } from './routes/industries_.architecture'
import { Route as BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRouteImport } from './routes/blog.why-businesses-need-growth-partner-not-marketing-agency'

const YoutubeGrowthChannelStrategyRoute =
  YoutubeGrowthChannelStrategyRouteImport.update({
    id: '/youtube-growth-channel-strategy',
    path: '/youtube-growth-channel-strategy',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteDevelopmentUnitedStatesRoute =
  WebsiteDevelopmentUnitedStatesRouteImport.update({
    id: '/website-development-united-states',
    path: '/website-development-united-states',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteDesignDevelopmentRoute =
  WebsiteDesignDevelopmentRouteImport.update({
    id: '/website-design-development',
    path: '/website-design-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnitedStateHomeRoute = UnitedStateHomeRouteImport.update({
  id: '/united-stateHome',
  path: '/united-stateHome',
  getParentRoute: () => rootRouteImport,
} as any)
const UiUxDesignProductEngineeringRoute =
  UiUxDesignProductEngineeringRouteImport.update({
    id: '/ui-ux-design-product-engineering',
    path: '/ui-ux-design-product-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsConditionRoute = TermsConditionRouteImport.update({
  id: '/terms-condition',
  path: '/terms-condition',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaMarketingRoute = SocialMediaMarketingRouteImport.update({
  id: '/social-media-marketing',
  path: '/social-media-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchVisibilityRoute = SearchVisibilityRouteImport.update({
  id: '/search-visibility',
  path: '/search-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRelationsReputationManagementRoute =
  PublicRelationsReputationManagementRouteImport.update({
    id: '/public-relations-reputation-management',
    path: '/public-relations-reputation-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastStrategyProductionRoute =
  PodcastStrategyProductionRouteImport.update({
    id: '/podcast-strategy-production',
    path: '/podcast-strategy-production',
    getParentRoute: () => rootRouteImport,
  } as any)
const PerformanceMarketingRoute = PerformanceMarketingRouteImport.update({
  id: '/performance-marketing',
  path: '/performance-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingProductBrandingRoute =
  PackagingProductBrandingRouteImport.update({
    id: '/packaging-product-branding',
    path: '/packaging-product-branding',
    getParentRoute: () => rootRouteImport,
  } as any)
const MotionGraphicsAnimationRoute = MotionGraphicsAnimationRouteImport.update({
  id: '/motion-graphics-animation',
  path: '/motion-graphics-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppDevelopmentRoute = MobileAppDevelopmentRouteImport.update({
  id: '/mobile-app-development',
  path: '/mobile-app-development',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCommunicationRoute = MarketingCommunicationRouteImport.update({
  id: '/marketing-communication',
  path: '/marketing-communication',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAutomationRoute = MarketingAutomationRouteImport.update({
  id: '/marketing-automation',
  path: '/marketing-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoVisualIdentityRoute = LogoVisualIdentityRouteImport.update({
  id: '/logo-visual-identity',
  path: '/logo-visual-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerAdvocacyCommunityMarketingRoute =
  InfluencerAdvocacyCommunityMarketingRouteImport.update({
    id: '/influencer-advocacy-community-marketing',
    path: '/influencer-advocacy-community-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthMarketingRoute = GrowthMarketingRouteImport.update({
  id: '/growth-marketing',
  path: '/growth-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventMarketingBrandExperiencesRoute =
  EventMarketingBrandExperiencesRouteImport.update({
    id: '/event-marketing-brand-experiences',
    path: '/event-marketing-brand-experiences',
    getParentRoute: () => rootRouteImport,
  } as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
const D2cRetailbrandRoute = D2cRetailbrandRouteImport.update({
  id: '/d2c-retailbrand',
  path: '/d2c-retailbrand',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmErpSolutionsRoute = CrmErpSolutionsRouteImport.update({
  id: '/crm-erp-solutions',
  path: '/crm-erp-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateFilmsVideoProductionRoute =
  CorporateFilmsVideoProductionRouteImport.update({
    id: '/corporate-films-video-production',
    path: '/corporate-films-video-production',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateCommunicationDesignRoute =
  CorporateCommunicationDesignRouteImport.update({
    id: '/corporate-communication-design',
    path: '/corporate-communication-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateB2bGrowthMarketingRoute =
  CorporateB2bGrowthMarketingRouteImport.update({
    id: '/corporate-b2b-growth-marketing',
    path: '/corporate-b2b-growth-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConversionOptimizationRoute = ConversionOptimizationRouteImport.update({
  id: '/conversion-optimization',
  path: '/conversion-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMarketingRoute = ContentMarketingRouteImport.update({
  id: '/content-marketing',
  path: '/content-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRexelloCastorsRoute = CaseRexelloCastorsRouteImport.update({
  id: '/case-rexello-castors',
  path: '/case-rexello-castors',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseMosUtilityRoute = CaseMosUtilityRouteImport.update({
  id: '/case-mos-utility',
  path: '/case-mos-utility',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseLivingConceptsRoute = CaseLivingConceptsRouteImport.update({
  id: '/case-living-concepts',
  path: '/case-living-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseKuwalSanamRoute = CaseKuwalSanamRouteImport.update({
  id: '/case-kuwal-sanam',
  path: '/case-kuwal-sanam',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCosmosSealsRoute = CaseCosmosSealsRouteImport.update({
  id: '/case-cosmos-seals',
  path: '/case-cosmos-seals',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseAmigoAcademyRoute = CaseAmigoAcademyRouteImport.update({
  id: '/case-amigo-academy',
  path: '/case-amigo-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingCreativeRoute = BrandingCreativeRouteImport.update({
  id: '/branding-creative',
  path: '/branding-creative',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStrategyRoute = BrandStrategyRouteImport.update({
  id: '/brand-strategy',
  path: '/brand-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsGrowthIntelligenceRoute =
  AnalyticsGrowthIntelligenceRouteImport.update({
    id: '/analytics-growth-intelligence',
    path: '/analytics-growth-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiWorkflowAutomationRoute = AiWorkflowAutomationRouteImport.update({
  id: '/ai-workflow-automation',
  path: '/ai-workflow-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTransformationRoute = AiTransformationRouteImport.update({
  id: '/ai-transformation',
  path: '/ai-transformation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStrategyReadinessAssessmentRoute =
  AiStrategyReadinessAssessmentRouteImport.update({
    id: '/ai-strategy-readiness-assessment',
    path: '/ai-strategy-readiness-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiCustomerExperienceSolutionsRoute =
  AiCustomerExperienceSolutionsRouteImport.update({
    id: '/ai-customer-experience-solutions',
    path: '/ai-customer-experience-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiContentMarketingSystemsRoute =
  AiContentMarketingSystemsRouteImport.update({
    id: '/ai-content-marketing-systems',
    path: '/ai-content-marketing-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesEnterpriseExperienceRoute =
  SuccessStoriesEnterpriseExperienceRouteImport.update({
    id: '/success-stories/enterprise-experience',
    path: '/success-stories/enterprise-experience',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesSaasTechnologyRoute =
  IndustriesSaasTechnologyRouteImport.update({
    id: '/industries_/saas-technology',
    path: '/industries/saas-technology',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesRealEstateRoute = IndustriesRealEstateRouteImport.update({
  id: '/industries_/real-estate',
  path: '/industries/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesManufacturingRoute = IndustriesManufacturingRouteImport.update({
  id: '/industries_/manufacturing',
  path: '/industries/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/industries_/healthcare',
  path: '/industries/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesFintechRoute = IndustriesFintechRouteImport.update({
  id: '/industries_/fintech',
  path: '/industries/fintech',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesEducationRoute = IndustriesEducationRouteImport.update({
  id: '/industries_/education',
  path: '/industries/education',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesD2cRetailbrandcopy2Route =
  IndustriesD2cRetailbrandcopy2RouteImport.update({
    id: '/industries_/d2c-retailbrand copy 2',
    path: '/industries/d2c-retailbrand copy 2',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesD2cRetailbrandRoute =
  IndustriesD2cRetailbrandRouteImport.update({
    id: '/industries_/d2c-retailbrand',
    path: '/industries/d2c-retailbrand',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesArchitectureRoute = IndustriesArchitectureRouteImport.update({
  id: '/industries_/architecture',
  path: '/industries/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute =
  BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRouteImport.update({
    id: '/why-businesses-need-growth-partner-not-marketing-agency',
    path: '/why-businesses-need-growth-partner-not-marketing-agency',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-content-marketing-systems': typeof AiContentMarketingSystemsRoute
  '/ai-customer-experience-solutions': typeof AiCustomerExperienceSolutionsRoute
  '/ai-strategy-readiness-assessment': typeof AiStrategyReadinessAssessmentRoute
  '/ai-transformation': typeof AiTransformationRoute
  '/ai-workflow-automation': typeof AiWorkflowAutomationRoute
  '/analytics-growth-intelligence': typeof AnalyticsGrowthIntelligenceRoute
  '/approvals': typeof ApprovalsRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-strategy': typeof BrandStrategyRoute
  '/branding-creative': typeof BrandingCreativeRoute
  '/careers': typeof CareersRoute
  '/case-amigo-academy': typeof CaseAmigoAcademyRoute
  '/case-cosmos-seals': typeof CaseCosmosSealsRoute
  '/case-kuwal-sanam': typeof CaseKuwalSanamRoute
  '/case-living-concepts': typeof CaseLivingConceptsRoute
  '/case-mos-utility': typeof CaseMosUtilityRoute
  '/case-rexello-castors': typeof CaseRexelloCastorsRoute
  '/contact': typeof ContactRoute
  '/content-marketing': typeof ContentMarketingRoute
  '/conversion-optimization': typeof ConversionOptimizationRoute
  '/corporate-b2b-growth-marketing': typeof CorporateB2bGrowthMarketingRoute
  '/corporate-communication-design': typeof CorporateCommunicationDesignRoute
  '/corporate-films-video-production': typeof CorporateFilmsVideoProductionRoute
  '/crm-erp-solutions': typeof CrmErpSolutionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/d2c-retailbrand': typeof D2cRetailbrandRoute
  '/event-marketing-brand-experiences': typeof EventMarketingBrandExperiencesRoute
  '/growth': typeof GrowthRoute
  '/growth-marketing': typeof GrowthMarketingRoute
  '/industries': typeof IndustriesRoute
  '/influencer-advocacy-community-marketing': typeof InfluencerAdvocacyCommunityMarketingRoute
  '/logo-visual-identity': typeof LogoVisualIdentityRoute
  '/marketing-automation': typeof MarketingAutomationRoute
  '/marketing-communication': typeof MarketingCommunicationRoute
  '/mobile-app-development': typeof MobileAppDevelopmentRoute
  '/motion-graphics-animation': typeof MotionGraphicsAnimationRoute
  '/packaging-product-branding': typeof PackagingProductBrandingRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/podcast-strategy-production': typeof PodcastStrategyProductionRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/public-relations-reputation-management': typeof PublicRelationsReputationManagementRoute
  '/refunds': typeof RefundsRoute
  '/real-estate': typeof RealEstateRoute
  '/search-visibility': typeof SearchVisibilityRoute
  '/services': typeof ServicesRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/technology': typeof TechnologyRoute
  '/terms-condition': typeof TermsConditionRoute
  '/ui-ux-design-product-engineering': typeof UiUxDesignProductEngineeringRoute
  '/united-stateHome': typeof UnitedStateHomeRoute
  '/website-design-development': typeof WebsiteDesignDevelopmentRoute
  '/website-development-united-states': typeof WebsiteDevelopmentUnitedStatesRoute
  '/youtube-growth-channel-strategy': typeof YoutubeGrowthChannelStrategyRoute
  '/blog/why-businesses-need-growth-partner-not-marketing-agency': typeof BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute
  '/industries/architecture': typeof IndustriesArchitectureRoute
  '/industries/d2c-retailbrand': typeof IndustriesD2cRetailbrandRoute
  '/industries/d2c-retailbrand copy 2': typeof IndustriesD2cRetailbrandcopy2Route
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/fintech': typeof IndustriesFintechRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/industries/saas-technology': typeof IndustriesSaasTechnologyRoute
  '/success-stories/enterprise-experience': typeof SuccessStoriesEnterpriseExperienceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-content-marketing-systems': typeof AiContentMarketingSystemsRoute
  '/ai-customer-experience-solutions': typeof AiCustomerExperienceSolutionsRoute
  '/ai-strategy-readiness-assessment': typeof AiStrategyReadinessAssessmentRoute
  '/ai-transformation': typeof AiTransformationRoute
  '/ai-workflow-automation': typeof AiWorkflowAutomationRoute
  '/analytics-growth-intelligence': typeof AnalyticsGrowthIntelligenceRoute
  '/approvals': typeof ApprovalsRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-strategy': typeof BrandStrategyRoute
  '/branding-creative': typeof BrandingCreativeRoute
  '/careers': typeof CareersRoute
  '/case-amigo-academy': typeof CaseAmigoAcademyRoute
  '/case-cosmos-seals': typeof CaseCosmosSealsRoute
  '/case-kuwal-sanam': typeof CaseKuwalSanamRoute
  '/case-living-concepts': typeof CaseLivingConceptsRoute
  '/case-mos-utility': typeof CaseMosUtilityRoute
  '/case-rexello-castors': typeof CaseRexelloCastorsRoute
  '/contact': typeof ContactRoute
  '/content-marketing': typeof ContentMarketingRoute
  '/conversion-optimization': typeof ConversionOptimizationRoute
  '/corporate-b2b-growth-marketing': typeof CorporateB2bGrowthMarketingRoute
  '/corporate-communication-design': typeof CorporateCommunicationDesignRoute
  '/corporate-films-video-production': typeof CorporateFilmsVideoProductionRoute
  '/crm-erp-solutions': typeof CrmErpSolutionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/d2c-retailbrand': typeof D2cRetailbrandRoute
  '/event-marketing-brand-experiences': typeof EventMarketingBrandExperiencesRoute
  '/growth': typeof GrowthRoute
  '/growth-marketing': typeof GrowthMarketingRoute
  '/industries': typeof IndustriesRoute
  '/influencer-advocacy-community-marketing': typeof InfluencerAdvocacyCommunityMarketingRoute
  '/logo-visual-identity': typeof LogoVisualIdentityRoute
  '/marketing-automation': typeof MarketingAutomationRoute
  '/marketing-communication': typeof MarketingCommunicationRoute
  '/mobile-app-development': typeof MobileAppDevelopmentRoute
  '/motion-graphics-animation': typeof MotionGraphicsAnimationRoute
  '/packaging-product-branding': typeof PackagingProductBrandingRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/podcast-strategy-production': typeof PodcastStrategyProductionRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/public-relations-reputation-management': typeof PublicRelationsReputationManagementRoute
  '/refunds': typeof RefundsRoute
  '/real-estate': typeof RealEstateRoute
  '/search-visibility': typeof SearchVisibilityRoute
  '/services': typeof ServicesRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/technology': typeof TechnologyRoute
  '/terms-condition': typeof TermsConditionRoute
  '/ui-ux-design-product-engineering': typeof UiUxDesignProductEngineeringRoute
  '/united-stateHome': typeof UnitedStateHomeRoute
  '/website-design-development': typeof WebsiteDesignDevelopmentRoute
  '/website-development-united-states': typeof WebsiteDevelopmentUnitedStatesRoute
  '/youtube-growth-channel-strategy': typeof YoutubeGrowthChannelStrategyRoute
  '/blog/why-businesses-need-growth-partner-not-marketing-agency': typeof BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute
  '/industries/architecture': typeof IndustriesArchitectureRoute
  '/industries/d2c-retailbrand': typeof IndustriesD2cRetailbrandRoute
  '/industries/d2c-retailbrand copy 2': typeof IndustriesD2cRetailbrandcopy2Route
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/fintech': typeof IndustriesFintechRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/industries/saas-technology': typeof IndustriesSaasTechnologyRoute
  '/success-stories/enterprise-experience': typeof SuccessStoriesEnterpriseExperienceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-content-marketing-systems': typeof AiContentMarketingSystemsRoute
  '/ai-customer-experience-solutions': typeof AiCustomerExperienceSolutionsRoute
  '/ai-strategy-readiness-assessment': typeof AiStrategyReadinessAssessmentRoute
  '/ai-transformation': typeof AiTransformationRoute
  '/ai-workflow-automation': typeof AiWorkflowAutomationRoute
  '/analytics-growth-intelligence': typeof AnalyticsGrowthIntelligenceRoute
  '/approvals': typeof ApprovalsRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-strategy': typeof BrandStrategyRoute
  '/branding-creative': typeof BrandingCreativeRoute
  '/careers': typeof CareersRoute
  '/case-amigo-academy': typeof CaseAmigoAcademyRoute
  '/case-cosmos-seals': typeof CaseCosmosSealsRoute
  '/case-kuwal-sanam': typeof CaseKuwalSanamRoute
  '/case-living-concepts': typeof CaseLivingConceptsRoute
  '/case-mos-utility': typeof CaseMosUtilityRoute
  '/case-rexello-castors': typeof CaseRexelloCastorsRoute
  '/contact': typeof ContactRoute
  '/content-marketing': typeof ContentMarketingRoute
  '/conversion-optimization': typeof ConversionOptimizationRoute
  '/corporate-b2b-growth-marketing': typeof CorporateB2bGrowthMarketingRoute
  '/corporate-communication-design': typeof CorporateCommunicationDesignRoute
  '/corporate-films-video-production': typeof CorporateFilmsVideoProductionRoute
  '/crm-erp-solutions': typeof CrmErpSolutionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/d2c-retailbrand': typeof D2cRetailbrandRoute
  '/event-marketing-brand-experiences': typeof EventMarketingBrandExperiencesRoute
  '/growth': typeof GrowthRoute
  '/growth-marketing': typeof GrowthMarketingRoute
  '/industries': typeof IndustriesRoute
  '/influencer-advocacy-community-marketing': typeof InfluencerAdvocacyCommunityMarketingRoute
  '/logo-visual-identity': typeof LogoVisualIdentityRoute
  '/marketing-automation': typeof MarketingAutomationRoute
  '/marketing-communication': typeof MarketingCommunicationRoute
  '/mobile-app-development': typeof MobileAppDevelopmentRoute
  '/motion-graphics-animation': typeof MotionGraphicsAnimationRoute
  '/packaging-product-branding': typeof PackagingProductBrandingRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/podcast-strategy-production': typeof PodcastStrategyProductionRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/public-relations-reputation-management': typeof PublicRelationsReputationManagementRoute
  '/refunds': typeof RefundsRoute
  '/real-estate': typeof RealEstateRoute
  '/search-visibility': typeof SearchVisibilityRoute
  '/services': typeof ServicesRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/technology': typeof TechnologyRoute
  '/terms-condition': typeof TermsConditionRoute
  '/ui-ux-design-product-engineering': typeof UiUxDesignProductEngineeringRoute
  '/united-stateHome': typeof UnitedStateHomeRoute
  '/website-design-development': typeof WebsiteDesignDevelopmentRoute
  '/website-development-united-states': typeof WebsiteDevelopmentUnitedStatesRoute
  '/youtube-growth-channel-strategy': typeof YoutubeGrowthChannelStrategyRoute
  '/blog/why-businesses-need-growth-partner-not-marketing-agency': typeof BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute
  '/industries_/architecture': typeof IndustriesArchitectureRoute
  '/industries_/d2c-retailbrand': typeof IndustriesD2cRetailbrandRoute
  '/industries_/d2c-retailbrand copy 2': typeof IndustriesD2cRetailbrandcopy2Route
  '/industries_/education': typeof IndustriesEducationRoute
  '/industries_/fintech': typeof IndustriesFintechRoute
  '/industries_/healthcare': typeof IndustriesHealthcareRoute
  '/industries_/manufacturing': typeof IndustriesManufacturingRoute
  '/industries_/real-estate': typeof IndustriesRealEstateRoute
  '/industries_/saas-technology': typeof IndustriesSaasTechnologyRoute
  '/success-stories/enterprise-experience': typeof SuccessStoriesEnterpriseExperienceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-content-marketing-systems'
    | '/ai-customer-experience-solutions'
    | '/ai-strategy-readiness-assessment'
    | '/ai-transformation'
    | '/ai-workflow-automation'
    | '/analytics-growth-intelligence'
    | '/approvals'
    | '/blog'
    | '/brand-strategy'
    | '/branding-creative'
    | '/careers'
    | '/case-amigo-academy'
    | '/case-cosmos-seals'
    | '/case-kuwal-sanam'
    | '/case-living-concepts'
    | '/case-mos-utility'
    | '/case-rexello-castors'
    | '/contact'
    | '/content-marketing'
    | '/conversion-optimization'
    | '/corporate-b2b-growth-marketing'
    | '/corporate-communication-design'
    | '/corporate-films-video-production'
    | '/crm-erp-solutions'
    | '/disclaimer'
    | '/d2c-retailbrand'
    | '/event-marketing-brand-experiences'
    | '/growth'
    | '/growth-marketing'
    | '/industries'
    | '/influencer-advocacy-community-marketing'
    | '/logo-visual-identity'
    | '/marketing-automation'
    | '/marketing-communication'
    | '/mobile-app-development'
    | '/motion-graphics-animation'
    | '/packaging-product-branding'
    | '/performance-marketing'
    | '/podcast-strategy-production'
    | '/portfolio'
    | '/privacy'
    | '/public-relations-reputation-management'
    | '/refunds'
    | '/real-estate'
    | '/search-visibility'
    | '/services'
    | '/social-media-marketing'
    | '/technology'
    | '/terms-condition'
    | '/ui-ux-design-product-engineering'
    | '/united-stateHome'
    | '/website-design-development'
    | '/website-development-united-states'
    | '/youtube-growth-channel-strategy'
    | '/blog/why-businesses-need-growth-partner-not-marketing-agency'
    | '/industries/architecture'
    | '/industries/d2c-retailbrand'
    | '/industries/d2c-retailbrand copy 2'
    | '/industries/education'
    | '/industries/fintech'
    | '/industries/healthcare'
    | '/industries/manufacturing'
    | '/industries/real-estate'
    | '/industries/saas-technology'
    | '/success-stories/enterprise-experience'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-content-marketing-systems'
    | '/ai-customer-experience-solutions'
    | '/ai-strategy-readiness-assessment'
    | '/ai-transformation'
    | '/ai-workflow-automation'
    | '/analytics-growth-intelligence'
    | '/approvals'
    | '/blog'
    | '/brand-strategy'
    | '/branding-creative'
    | '/careers'
    | '/case-amigo-academy'
    | '/case-cosmos-seals'
    | '/case-kuwal-sanam'
    | '/case-living-concepts'
    | '/case-mos-utility'
    | '/case-rexello-castors'
    | '/contact'
    | '/content-marketing'
    | '/conversion-optimization'
    | '/corporate-b2b-growth-marketing'
    | '/corporate-communication-design'
    | '/corporate-films-video-production'
    | '/crm-erp-solutions'
    | '/disclaimer'
    | '/d2c-retailbrand'
    | '/event-marketing-brand-experiences'
    | '/growth'
    | '/growth-marketing'
    | '/industries'
    | '/influencer-advocacy-community-marketing'
    | '/logo-visual-identity'
    | '/marketing-automation'
    | '/marketing-communication'
    | '/mobile-app-development'
    | '/motion-graphics-animation'
    | '/packaging-product-branding'
    | '/performance-marketing'
    | '/podcast-strategy-production'
    | '/portfolio'
    | '/privacy'
    | '/public-relations-reputation-management'
    | '/refunds'
    | '/real-estate'
    | '/search-visibility'
    | '/services'
    | '/social-media-marketing'
    | '/technology'
    | '/terms-condition'
    | '/ui-ux-design-product-engineering'
    | '/united-stateHome'
    | '/website-design-development'
    | '/website-development-united-states'
    | '/youtube-growth-channel-strategy'
    | '/blog/why-businesses-need-growth-partner-not-marketing-agency'
    | '/industries/architecture'
    | '/industries/d2c-retailbrand'
    | '/industries/d2c-retailbrand copy 2'
    | '/industries/education'
    | '/industries/fintech'
    | '/industries/healthcare'
    | '/industries/manufacturing'
    | '/industries/real-estate'
    | '/industries/saas-technology'
    | '/success-stories/enterprise-experience'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-content-marketing-systems'
    | '/ai-customer-experience-solutions'
    | '/ai-strategy-readiness-assessment'
    | '/ai-transformation'
    | '/ai-workflow-automation'
    | '/analytics-growth-intelligence'
    | '/approvals'
    | '/blog'
    | '/brand-strategy'
    | '/branding-creative'
    | '/careers'
    | '/case-amigo-academy'
    | '/case-cosmos-seals'
    | '/case-kuwal-sanam'
    | '/case-living-concepts'
    | '/case-mos-utility'
    | '/case-rexello-castors'
    | '/contact'
    | '/content-marketing'
    | '/conversion-optimization'
    | '/corporate-b2b-growth-marketing'
    | '/corporate-communication-design'
    | '/corporate-films-video-production'
    | '/crm-erp-solutions'
    | '/disclaimer'
    | '/d2c-retailbrand'
    | '/event-marketing-brand-experiences'
    | '/growth'
    | '/growth-marketing'
    | '/industries'
    | '/influencer-advocacy-community-marketing'
    | '/logo-visual-identity'
    | '/marketing-automation'
    | '/marketing-communication'
    | '/mobile-app-development'
    | '/motion-graphics-animation'
    | '/packaging-product-branding'
    | '/performance-marketing'
    | '/podcast-strategy-production'
    | '/portfolio'
    | '/privacy'
    | '/public-relations-reputation-management'
    | '/refunds'
    | '/real-estate'
    | '/search-visibility'
    | '/services'
    | '/social-media-marketing'
    | '/technology'
    | '/terms-condition'
    | '/ui-ux-design-product-engineering'
    | '/united-stateHome'
    | '/website-design-development'
    | '/website-development-united-states'
    | '/youtube-growth-channel-strategy'
    | '/blog/why-businesses-need-growth-partner-not-marketing-agency'
    | '/industries_/architecture'
    | '/industries_/d2c-retailbrand'
    | '/industries_/d2c-retailbrand copy 2'
    | '/industries_/education'
    | '/industries_/fintech'
    | '/industries_/healthcare'
    | '/industries_/manufacturing'
    | '/industries_/real-estate'
    | '/industries_/saas-technology'
    | '/success-stories/enterprise-experience'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiContentMarketingSystemsRoute: typeof AiContentMarketingSystemsRoute
  AiCustomerExperienceSolutionsRoute: typeof AiCustomerExperienceSolutionsRoute
  AiStrategyReadinessAssessmentRoute: typeof AiStrategyReadinessAssessmentRoute
  AiTransformationRoute: typeof AiTransformationRoute
  AiWorkflowAutomationRoute: typeof AiWorkflowAutomationRoute
  AnalyticsGrowthIntelligenceRoute: typeof AnalyticsGrowthIntelligenceRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BlogRoute: typeof BlogRouteWithChildren
  BrandStrategyRoute: typeof BrandStrategyRoute
  BrandingCreativeRoute: typeof BrandingCreativeRoute
  CareersRoute: typeof CareersRoute
  CaseAmigoAcademyRoute: typeof CaseAmigoAcademyRoute
  CaseCosmosSealsRoute: typeof CaseCosmosSealsRoute
  CaseKuwalSanamRoute: typeof CaseKuwalSanamRoute
  CaseLivingConceptsRoute: typeof CaseLivingConceptsRoute
  CaseMosUtilityRoute: typeof CaseMosUtilityRoute
  CaseRexelloCastorsRoute: typeof CaseRexelloCastorsRoute
  ContactRoute: typeof ContactRoute
  ContentMarketingRoute: typeof ContentMarketingRoute
  ConversionOptimizationRoute: typeof ConversionOptimizationRoute
  CorporateB2bGrowthMarketingRoute: typeof CorporateB2bGrowthMarketingRoute
  CorporateCommunicationDesignRoute: typeof CorporateCommunicationDesignRoute
  CorporateFilmsVideoProductionRoute: typeof CorporateFilmsVideoProductionRoute
  CrmErpSolutionsRoute: typeof CrmErpSolutionsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  D2cRetailbrandRoute: typeof D2cRetailbrandRoute
  EventMarketingBrandExperiencesRoute: typeof EventMarketingBrandExperiencesRoute
  GrowthRoute: typeof GrowthRoute
  GrowthMarketingRoute: typeof GrowthMarketingRoute
  IndustriesRoute: typeof IndustriesRoute
  InfluencerAdvocacyCommunityMarketingRoute: typeof InfluencerAdvocacyCommunityMarketingRoute
  LogoVisualIdentityRoute: typeof LogoVisualIdentityRoute
  MarketingAutomationRoute: typeof MarketingAutomationRoute
  MarketingCommunicationRoute: typeof MarketingCommunicationRoute
  MobileAppDevelopmentRoute: typeof MobileAppDevelopmentRoute
  MotionGraphicsAnimationRoute: typeof MotionGraphicsAnimationRoute
  PackagingProductBrandingRoute: typeof PackagingProductBrandingRoute
  PerformanceMarketingRoute: typeof PerformanceMarketingRoute
  PodcastStrategyProductionRoute: typeof PodcastStrategyProductionRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicRelationsReputationManagementRoute: typeof PublicRelationsReputationManagementRoute
  RefundsRoute: typeof RefundsRoute
  RealEstateRoute: typeof RealEstateRoute
  SearchVisibilityRoute: typeof SearchVisibilityRoute
  ServicesRoute: typeof ServicesRoute
  SocialMediaMarketingRoute: typeof SocialMediaMarketingRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsConditionRoute: typeof TermsConditionRoute
  UiUxDesignProductEngineeringRoute: typeof UiUxDesignProductEngineeringRoute
  UnitedStateHomeRoute: typeof UnitedStateHomeRoute
  WebsiteDesignDevelopmentRoute: typeof WebsiteDesignDevelopmentRoute
  WebsiteDevelopmentUnitedStatesRoute: typeof WebsiteDevelopmentUnitedStatesRoute
  YoutubeGrowthChannelStrategyRoute: typeof YoutubeGrowthChannelStrategyRoute
  IndustriesArchitectureRoute: typeof IndustriesArchitectureRoute
  IndustriesD2cRetailbrandRoute: typeof IndustriesD2cRetailbrandRoute
  IndustriesD2cRetailbrandcopy2Route: typeof IndustriesD2cRetailbrandcopy2Route
  IndustriesEducationRoute: typeof IndustriesEducationRoute
  IndustriesFintechRoute: typeof IndustriesFintechRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesManufacturingRoute: typeof IndustriesManufacturingRoute
  IndustriesRealEstateRoute: typeof IndustriesRealEstateRoute
  IndustriesSaasTechnologyRoute: typeof IndustriesSaasTechnologyRoute
  SuccessStoriesEnterpriseExperienceRoute: typeof SuccessStoriesEnterpriseExperienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-growth-channel-strategy': {
      id: '/youtube-growth-channel-strategy'
      path: '/youtube-growth-channel-strategy'
      fullPath: '/youtube-growth-channel-strategy'
      preLoaderRoute: typeof YoutubeGrowthChannelStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-development-united-states': {
      id: '/website-development-united-states'
      path: '/website-development-united-states'
      fullPath: '/website-development-united-states'
      preLoaderRoute: typeof WebsiteDevelopmentUnitedStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-design-development': {
      id: '/website-design-development'
      path: '/website-design-development'
      fullPath: '/website-design-development'
      preLoaderRoute: typeof WebsiteDesignDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/united-stateHome': {
      id: '/united-stateHome'
      path: '/united-stateHome'
      fullPath: '/united-stateHome'
      preLoaderRoute: typeof UnitedStateHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-ux-design-product-engineering': {
      id: '/ui-ux-design-product-engineering'
      path: '/ui-ux-design-product-engineering'
      fullPath: '/ui-ux-design-product-engineering'
      preLoaderRoute: typeof UiUxDesignProductEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-condition': {
      id: '/terms-condition'
      path: '/terms-condition'
      fullPath: '/terms-condition'
      preLoaderRoute: typeof TermsConditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-marketing': {
      id: '/social-media-marketing'
      path: '/social-media-marketing'
      fullPath: '/social-media-marketing'
      preLoaderRoute: typeof SocialMediaMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-visibility': {
      id: '/search-visibility'
      path: '/search-visibility'
      fullPath: '/search-visibility'
      preLoaderRoute: typeof SearchVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-relations-reputation-management': {
      id: '/public-relations-reputation-management'
      path: '/public-relations-reputation-management'
      fullPath: '/public-relations-reputation-management'
      preLoaderRoute: typeof PublicRelationsReputationManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast-strategy-production': {
      id: '/podcast-strategy-production'
      path: '/podcast-strategy-production'
      fullPath: '/podcast-strategy-production'
      preLoaderRoute: typeof PodcastStrategyProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-marketing': {
      id: '/performance-marketing'
      path: '/performance-marketing'
      fullPath: '/performance-marketing'
      preLoaderRoute: typeof PerformanceMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging-product-branding': {
      id: '/packaging-product-branding'
      path: '/packaging-product-branding'
      fullPath: '/packaging-product-branding'
      preLoaderRoute: typeof PackagingProductBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-graphics-animation': {
      id: '/motion-graphics-animation'
      path: '/motion-graphics-animation'
      fullPath: '/motion-graphics-animation'
      preLoaderRoute: typeof MotionGraphicsAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app-development': {
      id: '/mobile-app-development'
      path: '/mobile-app-development'
      fullPath: '/mobile-app-development'
      preLoaderRoute: typeof MobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-communication': {
      id: '/marketing-communication'
      path: '/marketing-communication'
      fullPath: '/marketing-communication'
      preLoaderRoute: typeof MarketingCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-automation': {
      id: '/marketing-automation'
      path: '/marketing-automation'
      fullPath: '/marketing-automation'
      preLoaderRoute: typeof MarketingAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-visual-identity': {
      id: '/logo-visual-identity'
      path: '/logo-visual-identity'
      fullPath: '/logo-visual-identity'
      preLoaderRoute: typeof LogoVisualIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer-advocacy-community-marketing': {
      id: '/influencer-advocacy-community-marketing'
      path: '/influencer-advocacy-community-marketing'
      fullPath: '/influencer-advocacy-community-marketing'
      preLoaderRoute: typeof InfluencerAdvocacyCommunityMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-marketing': {
      id: '/growth-marketing'
      path: '/growth-marketing'
      fullPath: '/growth-marketing'
      preLoaderRoute: typeof GrowthMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-marketing-brand-experiences': {
      id: '/event-marketing-brand-experiences'
      path: '/event-marketing-brand-experiences'
      fullPath: '/event-marketing-brand-experiences'
      preLoaderRoute: typeof EventMarketingBrandExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
    '/d2c-retailbrand': {
      id: '/d2c-retailbrand'
      path: '/d2c-retailbrand'
      fullPath: '/d2c-retailbrand'
      preLoaderRoute: typeof D2cRetailbrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-erp-solutions': {
      id: '/crm-erp-solutions'
      path: '/crm-erp-solutions'
      fullPath: '/crm-erp-solutions'
      preLoaderRoute: typeof CrmErpSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-films-video-production': {
      id: '/corporate-films-video-production'
      path: '/corporate-films-video-production'
      fullPath: '/corporate-films-video-production'
      preLoaderRoute: typeof CorporateFilmsVideoProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-communication-design': {
      id: '/corporate-communication-design'
      path: '/corporate-communication-design'
      fullPath: '/corporate-communication-design'
      preLoaderRoute: typeof CorporateCommunicationDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-b2b-growth-marketing': {
      id: '/corporate-b2b-growth-marketing'
      path: '/corporate-b2b-growth-marketing'
      fullPath: '/corporate-b2b-growth-marketing'
      preLoaderRoute: typeof CorporateB2bGrowthMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion-optimization': {
      id: '/conversion-optimization'
      path: '/conversion-optimization'
      fullPath: '/conversion-optimization'
      preLoaderRoute: typeof ConversionOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-marketing': {
      id: '/content-marketing'
      path: '/content-marketing'
      fullPath: '/content-marketing'
      preLoaderRoute: typeof ContentMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-rexello-castors': {
      id: '/case-rexello-castors'
      path: '/case-rexello-castors'
      fullPath: '/case-rexello-castors'
      preLoaderRoute: typeof CaseRexelloCastorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-mos-utility': {
      id: '/case-mos-utility'
      path: '/case-mos-utility'
      fullPath: '/case-mos-utility'
      preLoaderRoute: typeof CaseMosUtilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-living-concepts': {
      id: '/case-living-concepts'
      path: '/case-living-concepts'
      fullPath: '/case-living-concepts'
      preLoaderRoute: typeof CaseLivingConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-kuwal-sanam': {
      id: '/case-kuwal-sanam'
      path: '/case-kuwal-sanam'
      fullPath: '/case-kuwal-sanam'
      preLoaderRoute: typeof CaseKuwalSanamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-cosmos-seals': {
      id: '/case-cosmos-seals'
      path: '/case-cosmos-seals'
      fullPath: '/case-cosmos-seals'
      preLoaderRoute: typeof CaseCosmosSealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-amigo-academy': {
      id: '/case-amigo-academy'
      path: '/case-amigo-academy'
      fullPath: '/case-amigo-academy'
      preLoaderRoute: typeof CaseAmigoAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding-creative': {
      id: '/branding-creative'
      path: '/branding-creative'
      fullPath: '/branding-creative'
      preLoaderRoute: typeof BrandingCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-strategy': {
      id: '/brand-strategy'
      path: '/brand-strategy'
      fullPath: '/brand-strategy'
      preLoaderRoute: typeof BrandStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics-growth-intelligence': {
      id: '/analytics-growth-intelligence'
      path: '/analytics-growth-intelligence'
      fullPath: '/analytics-growth-intelligence'
      preLoaderRoute: typeof AnalyticsGrowthIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workflow-automation': {
      id: '/ai-workflow-automation'
      path: '/ai-workflow-automation'
      fullPath: '/ai-workflow-automation'
      preLoaderRoute: typeof AiWorkflowAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-transformation': {
      id: '/ai-transformation'
      path: '/ai-transformation'
      fullPath: '/ai-transformation'
      preLoaderRoute: typeof AiTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-strategy-readiness-assessment': {
      id: '/ai-strategy-readiness-assessment'
      path: '/ai-strategy-readiness-assessment'
      fullPath: '/ai-strategy-readiness-assessment'
      preLoaderRoute: typeof AiStrategyReadinessAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-customer-experience-solutions': {
      id: '/ai-customer-experience-solutions'
      path: '/ai-customer-experience-solutions'
      fullPath: '/ai-customer-experience-solutions'
      preLoaderRoute: typeof AiCustomerExperienceSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-content-marketing-systems': {
      id: '/ai-content-marketing-systems'
      path: '/ai-content-marketing-systems'
      fullPath: '/ai-content-marketing-systems'
      preLoaderRoute: typeof AiContentMarketingSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/enterprise-experience': {
      id: '/success-stories/enterprise-experience'
      path: '/success-stories/enterprise-experience'
      fullPath: '/success-stories/enterprise-experience'
      preLoaderRoute: typeof SuccessStoriesEnterpriseExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/saas-technology': {
      id: '/industries_/saas-technology'
      path: '/industries/saas-technology'
      fullPath: '/industries/saas-technology'
      preLoaderRoute: typeof IndustriesSaasTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/real-estate': {
      id: '/industries_/real-estate'
      path: '/industries/real-estate'
      fullPath: '/industries/real-estate'
      preLoaderRoute: typeof IndustriesRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/manufacturing': {
      id: '/industries_/manufacturing'
      path: '/industries/manufacturing'
      fullPath: '/industries/manufacturing'
      preLoaderRoute: typeof IndustriesManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/healthcare': {
      id: '/industries_/healthcare'
      path: '/industries/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/fintech': {
      id: '/industries_/fintech'
      path: '/industries/fintech'
      fullPath: '/industries/fintech'
      preLoaderRoute: typeof IndustriesFintechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/education': {
      id: '/industries_/education'
      path: '/industries/education'
      fullPath: '/industries/education'
      preLoaderRoute: typeof IndustriesEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/d2c-retailbrand copy 2': {
      id: '/industries_/d2c-retailbrand copy 2'
      path: '/industries/d2c-retailbrand copy 2'
      fullPath: '/industries/d2c-retailbrand copy 2'
      preLoaderRoute: typeof IndustriesD2cRetailbrandcopy2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/d2c-retailbrand': {
      id: '/industries_/d2c-retailbrand'
      path: '/industries/d2c-retailbrand'
      fullPath: '/industries/d2c-retailbrand'
      preLoaderRoute: typeof IndustriesD2cRetailbrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries_/architecture': {
      id: '/industries_/architecture'
      path: '/industries/architecture'
      fullPath: '/industries/architecture'
      preLoaderRoute: typeof IndustriesArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-businesses-need-growth-partner-not-marketing-agency': {
      id: '/blog/why-businesses-need-growth-partner-not-marketing-agency'
      path: '/why-businesses-need-growth-partner-not-marketing-agency'
      fullPath: '/blog/why-businesses-need-growth-partner-not-marketing-agency'
      preLoaderRoute: typeof BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute: typeof BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute:
    BlogWhyBusinessesNeedGrowthPartnerNotMarketingAgencyRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiContentMarketingSystemsRoute: AiContentMarketingSystemsRoute,
  AiCustomerExperienceSolutionsRoute: AiCustomerExperienceSolutionsRoute,
  AiStrategyReadinessAssessmentRoute: AiStrategyReadinessAssessmentRoute,
  AiTransformationRoute: AiTransformationRoute,
  AiWorkflowAutomationRoute: AiWorkflowAutomationRoute,
  AnalyticsGrowthIntelligenceRoute: AnalyticsGrowthIntelligenceRoute,
  ApprovalsRoute: ApprovalsRoute,
  BlogRoute: BlogRouteWithChildren,
  BrandStrategyRoute: BrandStrategyRoute,
  BrandingCreativeRoute: BrandingCreativeRoute,
  CareersRoute: CareersRoute,
  CaseAmigoAcademyRoute: CaseAmigoAcademyRoute,
  CaseCosmosSealsRoute: CaseCosmosSealsRoute,
  CaseKuwalSanamRoute: CaseKuwalSanamRoute,
  CaseLivingConceptsRoute: CaseLivingConceptsRoute,
  CaseMosUtilityRoute: CaseMosUtilityRoute,
  CaseRexelloCastorsRoute: CaseRexelloCastorsRoute,
  ContactRoute: ContactRoute,
  ContentMarketingRoute: ContentMarketingRoute,
  ConversionOptimizationRoute: ConversionOptimizationRoute,
  CorporateB2bGrowthMarketingRoute: CorporateB2bGrowthMarketingRoute,
  CorporateCommunicationDesignRoute: CorporateCommunicationDesignRoute,
  CorporateFilmsVideoProductionRoute: CorporateFilmsVideoProductionRoute,
  CrmErpSolutionsRoute: CrmErpSolutionsRoute,
  DisclaimerRoute: DisclaimerRoute,
  D2cRetailbrandRoute: D2cRetailbrandRoute,
  EventMarketingBrandExperiencesRoute: EventMarketingBrandExperiencesRoute,
  GrowthRoute: GrowthRoute,
  GrowthMarketingRoute: GrowthMarketingRoute,
  IndustriesRoute: IndustriesRoute,
  InfluencerAdvocacyCommunityMarketingRoute:
    InfluencerAdvocacyCommunityMarketingRoute,
  LogoVisualIdentityRoute: LogoVisualIdentityRoute,
  MarketingAutomationRoute: MarketingAutomationRoute,
  MarketingCommunicationRoute: MarketingCommunicationRoute,
  MobileAppDevelopmentRoute: MobileAppDevelopmentRoute,
  MotionGraphicsAnimationRoute: MotionGraphicsAnimationRoute,
  PackagingProductBrandingRoute: PackagingProductBrandingRoute,
  PerformanceMarketingRoute: PerformanceMarketingRoute,
  PodcastStrategyProductionRoute: PodcastStrategyProductionRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  PublicRelationsReputationManagementRoute:
    PublicRelationsReputationManagementRoute,
  RefundsRoute: RefundsRoute,
  RealEstateRoute: RealEstateRoute,
  SearchVisibilityRoute: SearchVisibilityRoute,
  ServicesRoute: ServicesRoute,
  SocialMediaMarketingRoute: SocialMediaMarketingRoute,
  TechnologyRoute: TechnologyRoute,
  TermsConditionRoute: TermsConditionRoute,
  UiUxDesignProductEngineeringRoute: UiUxDesignProductEngineeringRoute,
  UnitedStateHomeRoute: UnitedStateHomeRoute,
  WebsiteDesignDevelopmentRoute: WebsiteDesignDevelopmentRoute,
  WebsiteDevelopmentUnitedStatesRoute: WebsiteDevelopmentUnitedStatesRoute,
  YoutubeGrowthChannelStrategyRoute: YoutubeGrowthChannelStrategyRoute,
  IndustriesArchitectureRoute: IndustriesArchitectureRoute,
  IndustriesD2cRetailbrandRoute: IndustriesD2cRetailbrandRoute,
  IndustriesD2cRetailbrandcopy2Route: IndustriesD2cRetailbrandcopy2Route,
  IndustriesEducationRoute: IndustriesEducationRoute,
  IndustriesFintechRoute: IndustriesFintechRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesManufacturingRoute: IndustriesManufacturingRoute,
  IndustriesRealEstateRoute: IndustriesRealEstateRoute,
  IndustriesSaasTechnologyRoute: IndustriesSaasTechnologyRoute,
  SuccessStoriesEnterpriseExperienceRoute:
    SuccessStoriesEnterpriseExperienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
